services:
  memory_frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - memory_backend
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
  memory_backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - memory_db
    environment:
      - DATABASE_URL=postgresql://user:password@memory_db:5432/memory
    volumes:
      - ./backend:/app
  memory_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memory
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./ressources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  db_data: 